pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Anjali936/three-tier-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    sudo apt-get update
                    sudo apt-get install -y nginx nodejs npm curl
                    sudo npm install -g pm2
                '''
            }
        }

        stage('Build Frontend (React)') {
            steps {
                dir('application-code/web-tier') {
                    sh '''
                        npm install
                        npm run build
                        ls -l build
                    '''
                }
            }
        }

        stage('Deploy Frontend to Nginx') {
            steps {
                sh '''
                    sudo cp application-code/nginx.conf /etc/nginx/nginx.conf || true
                    sudo rm -rf /var/www/html/*
                    sudo cp -r application-code/web-tier/build/* /var/www/html/
                    sudo nginx -t
                    sudo systemctl restart nginx
                    sudo systemctl enable nginx
                '''
            }
        }

        stage('Start Backend (Node.js API)') {
            steps {
                dir('application-code/app-tier') {
                    sh '''
                        npm install
                        pm2 start index.js || pm2 restart index.js
                        pm2 save
                    '''
                }
            }
        }
    }
}
